# Descomenta y rellena cuando haya una vía de financiación pública.
# Ver https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-funding-a-developer
# github: [DiegoVicenteCamara]
# ko_fi: ""
# open_collective: ""
# custom: [""]
